"""
src/provenance.py
=================
F25 — Provenance and Reproducibility Logging (Cross-cutting).

Provides standardized hashing, git commit resolution, seed initialization,
and provenance dictionary construction across all pipeline stages.

Every artifact JSON generated by the pipeline must include:
  - config_hash: MD5 hex of sorted config dictionary
  - code_commit: Git commit SHA (or 'unknown' / 'untracked')
  - matcher_params_hash: MD5 hex of matcher parameters dictionary
  - created_at: ISO 8601 UTC timestamp
  - seed: Global random seed used for reproducibility

References:
  - FEATURES.md F25 (Provenance and Reproducibility Logging)
  - PROGRESS.md §6.1 (Provenance)
  - CONFIGURATION.md §1 (Global Configuration)
"""
from __future__ import annotations

import datetime
import hashlib
import json
import logging
import os
import random
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional, Union

import numpy as np

logger = logging.getLogger(__name__)


def hash_config(cfg: Union[Dict[str, Any], str, Path, None]) -> str:
    """
    Compute MD5 hash of configuration dictionary or YAML file content.

    Ensures canonical sorting and formatting so identical configurations
    always yield the exact same hash across platforms.

    Parameters:
      cfg: Dict, YAML string, Path to config file, or None

    Returns:
      32-character hex MD5 string
    """
    if cfg is None:
        return hashlib.md5(b"{}").hexdigest()

    if isinstance(cfg, (str, Path)):
        path = Path(cfg)
        if path.exists() and path.is_file():
            content = path.read_bytes()
            return hashlib.md5(content).hexdigest()
        else:
            return hashlib.md5(str(cfg).encode("utf-8")).hexdigest()

    try:
        serialized = json.dumps(cfg, sort_keys=True, default=str)
        return hashlib.md5(serialized.encode("utf-8")).hexdigest()
    except Exception as exc:
        logger.warning("Failed to serialize config for hashing: %s", exc)
        return hashlib.md5(str(cfg).encode("utf-8")).hexdigest()


def hash_matcher_params(params: Optional[Dict[str, Any]]) -> str:
    """
    Compute MD5 hash of matcher hyperparameters dictionary.

    Parameters:
      params: Dict of matcher parameters or None

    Returns:
      32-character hex MD5 string
    """
    if not params:
        return hashlib.md5(b"{}").hexdigest()
    try:
        serialized = json.dumps(params, sort_keys=True, default=str)
        return hashlib.md5(serialized.encode("utf-8")).hexdigest()
    except Exception as exc:
        logger.warning("Failed to serialize matcher params: %s", exc)
        return hashlib.md5(str(params).encode("utf-8")).hexdigest()


def get_code_commit(repo_root: Optional[Union[str, Path]] = None) -> str:
    """
    Retrieve the current Git commit SHA-1 hash.

    Parameters:
      repo_root: Optional path to repository root directory

    Returns:
      40-character commit hash, or 'untracked' / 'unknown' on failure
    """
    cwd = Path(repo_root) if repo_root else Path(__file__).resolve().parent.parent
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=cwd,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        if len(out) == 40:
            return out
        return out or "unknown"
    except Exception:
        return "unknown"


def set_global_seed(seed: int = 42) -> int:
    """
    Set deterministic random seeds across Python random and NumPy.

    Parameters:
      seed: Integer seed (default: 42 from CONFIGURATION.md)

    Returns:
      The integer seed that was set
    """
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    return seed


def build_provenance(
    config: Optional[Dict[str, Any]] = None,
    matcher_params: Optional[Dict[str, Any]] = None,
    seed: Optional[int] = None,
    repo_root: Optional[Union[str, Path]] = None,
) -> Dict[str, Any]:
    """
    Construct standard F25 provenance dictionary for inclusion in artifact JSONs.

    Parameters:
      config: Full or sub-module configuration dictionary
      matcher_params: Optional matcher-specific parameter dictionary
      seed: Global random seed used (defaults to config['global']['seed'] or 42)
      repo_root: Optional repository root path for git lookup

    Returns:
      Dictionary conforming to INTERFACES.md provenance schema:
        {
          "config_hash": "...",
          "code_commit": "...",
          "matcher_params_hash": "...",
          "created_at": "YYYY-MM-DDTHH:MM:SSZ",
          "seed": 42
        }
    """
    if seed is None and config and "global" in config:
        seed = int(config["global"].get("seed", 42))
    elif seed is None:
        seed = 42

    now_utc = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    return {
        "config_hash": hash_config(config),
        "code_commit": get_code_commit(repo_root=repo_root),
        "matcher_params_hash": hash_matcher_params(matcher_params),
        "created_at": now_utc,
        "seed": int(seed),
    }
